// SuperCollider Intensiv 01
// 28.10.2020

// Fragen zur Übungsaufgabe/Abgabe?

// Fragen zu SuperCollider?

// Ausführung, Blöcke und Post Window

// Syntax, Messages
// Help: Messages

// abs, sin, pow

// Operatorenpräzedenz

// Funktionen, Argumente

// Ndef

// Symbole

// play, stop, fadeTime

// Operationen auf Signale

// UGens

// ar/kr

// Signal-Umfang

// Unipolar/Bipolar

// .poll

// MouseX, MouseY, Line, XLine

// Argumente, NdefMixer

// .set

// var

